### ISSUE TITLE
x86补丁修改后什么样子？都是修改索引0那一个吗？

### ISSUE THREAD

**Issue by jay763190097** [daliansky/P-little#3]

**Comment by williambj1** [comment]
请进一步详细说明

**Comment by jay763190097** [comment]
![image](https://user-images.githubusercontent.com/16317178/84125409-16460200-aa6f-11ea-9c15-e359f23c07e5.png)
就是这个描述不太清楚，都只要改0的那个吗？是那样改的吗

**Comment by williambj1** [comment]
热补丁不是拿来打 DSDT 补丁的，请提前阅读仓库里的其他基础教程

**Comment by jay763190097** [comment]
恕我愚钝，没看到教程和用法在哪。。。

**Comment by jay763190097** [comment]
@williambj1 我现在的问题是x86没加载，没真正变频
```
MacBook-Pro:~ jay$ sysctl machdep.xcpm.mode
machdep.xcpm.mode: 1
MacBook-Pro:~ jay$ sysctl -n machdep.xcpm.vectors_loaded_count
0
MacBook-Pro:~ jay$ kextstat|grep -y x86plat
MacBook-Pro:~ jay$ kextstat|grep -y appleintelcpu
```

**Comment by williambj1** [comment]
忘了这是 P-Little 了，不好意思。。。。。

去参考 oc-little 吧，那里描述更齐全一些，直接用 SSDT 热补丁就好，没必要整合进 DSDT。

**Comment by jay763190097** [comment]
描述也差不多，都。。。我还是直接勾选来驱动x86吧
